/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pantallas;

import DTOs.ChatDTO;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JTextPane;
import javax.swing.SwingUtilities;
import javax.swing.text.BadLocationException;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author LuisaM
 */
public class ChatPanel extends javax.swing.JPanel {

    protected static ChatDTO chatSeleccionado;
    private static javax.swing.JTextPane mensajes;
    /**
     * Creates new form ChatPanel
     */
    public ChatPanel() {
        initComponents();
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        infoContacto = new javax.swing.JPanel();
        icon = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        bttnEmisor = new javax.swing.JRadioButton();
        bttnReceptor = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        msgBarPanel = new javax.swing.JPanel();
        msgField = new javax.swing.JTextField();
        sendBtn = new javax.swing.JButton();
        photoBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoContacto.setBackground(new java.awt.Color(86, 209, 246));
        infoContacto.setPreferredSize(new java.awt.Dimension(393, 140));
        infoContacto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon.setMaximumSize(new java.awt.Dimension(64, 64));
        icon.setMinimumSize(new java.awt.Dimension(64, 64));
        icon.setPreferredSize(new java.awt.Dimension(64, 64));
        icon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconActionPerformed(evt);
            }
        });
        infoContacto.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 29, -1, -1));

        backBtn.setMaximumSize(new java.awt.Dimension(32, 32));
        backBtn.setMinimumSize(new java.awt.Dimension(32, 32));
        backBtn.setPreferredSize(new java.awt.Dimension(32, 32));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        infoContacto.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 29, -1, -1));

        nameLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setPreferredSize(new java.awt.Dimension(220, 26));
        infoContacto.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 105, -1, -1));

        bttnEmisor.setBackground(new java.awt.Color(86, 209, 246));
        buttonGroup1.add(bttnEmisor);
        bttnEmisor.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        bttnEmisor.setForeground(new java.awt.Color(0, 0, 0));
        bttnEmisor.setText("emisor");
        bttnEmisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnEmisorActionPerformed(evt);
            }
        });
        infoContacto.add(bttnEmisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 77, -1));

        bttnReceptor.setBackground(new java.awt.Color(86, 209, 246));
        buttonGroup1.add(bttnReceptor);
        bttnReceptor.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        bttnReceptor.setForeground(new java.awt.Color(0, 0, 0));
        bttnReceptor.setText("receptor");
        bttnReceptor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnReceptorActionPerformed(evt);
            }
        });
        infoContacto.add(bttnReceptor, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        jLabel1.setBackground(new java.awt.Color(86, 209, 246));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Tipo de mensaje:");
        infoContacto.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        add(infoContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        scroll.setBackground(new java.awt.Color(255, 255, 255));
        scroll.setForeground(new java.awt.Color(0, 0, 0));
        scroll.setMaximumSize(new java.awt.Dimension(393, 450));
        scroll.setMinimumSize(new java.awt.Dimension(393, 450));
        scroll.setPreferredSize(new java.awt.Dimension(393, 450));
        add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        msgBarPanel.setBackground(new java.awt.Color(81, 81, 81));
        msgBarPanel.setMaximumSize(new java.awt.Dimension(390, 70));
        msgBarPanel.setMinimumSize(new java.awt.Dimension(390, 70));
        msgBarPanel.setPreferredSize(new java.awt.Dimension(393, 80));

        msgField.setBackground(new java.awt.Color(255, 255, 255));
        msgField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        msgField.setForeground(new java.awt.Color(0, 0, 0));
        msgField.setMaximumSize(new java.awt.Dimension(280, 34));
        msgField.setMinimumSize(new java.awt.Dimension(280, 34));
        msgField.setPreferredSize(new java.awt.Dimension(280, 34));
        msgField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                msgFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                msgFieldFocusLost(evt);
            }
        });
        msgField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msgFieldActionPerformed(evt);
            }
        });

        sendBtn.setMaximumSize(new java.awt.Dimension(32, 32));
        sendBtn.setMinimumSize(new java.awt.Dimension(32, 32));
        sendBtn.setPreferredSize(new java.awt.Dimension(32, 32));
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });

        photoBtn.setMaximumSize(new java.awt.Dimension(32, 32));
        photoBtn.setMinimumSize(new java.awt.Dimension(32, 32));
        photoBtn.setPreferredSize(new java.awt.Dimension(32, 32));

        javax.swing.GroupLayout msgBarPanelLayout = new javax.swing.GroupLayout(msgBarPanel);
        msgBarPanel.setLayout(msgBarPanelLayout);
        msgBarPanelLayout.setHorizontalGroup(
            msgBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(msgBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(photoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(msgField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        msgBarPanelLayout.setVerticalGroup(
            msgBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(msgBarPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(msgBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(msgBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(msgField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(photoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        add(msgBarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, -1, 110));
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        volver();
    }//GEN-LAST:event_backBtnActionPerformed

    private void iconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iconActionPerformed

    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendBtnActionPerformed

    private void msgFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_msgFieldFocusLost
        // TODO add your handling code here:
        if(msgField.getText().isEmpty())msgField.setText("Escribe un mensaje");
    }//GEN-LAST:event_msgFieldFocusLost

    private void msgFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_msgFieldFocusGained
        // TODO add your handling code here:
        if(msgField.getText().equals("Escribe un mensaje"))msgField.setText("");
    }//GEN-LAST:event_msgFieldFocusGained

    private void msgFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msgFieldActionPerformed
        // TODO add your handling code here:
        enviarMensaje();
    }//GEN-LAST:event_msgFieldActionPerformed

    private void bttnReceptorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnReceptorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttnReceptorActionPerformed

    private void bttnEmisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnEmisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttnEmisorActionPerformed

    private void iniciar(){
        setIcono(backBtn,"back.png");
        setIcono(sendBtn, "send-message.png");
        setIcono(photoBtn, "camera.png");
        msgField.setText("Escribe un mensaje");
        msgField.setForeground(Color.LIGHT_GRAY);
        bttnEmisor.setSelected(true);
    }
    
    private void enviarMensaje() {
        boolean emisor=bttnEmisor.isSelected();
        String msj="";
        msj=msj.concat(emisor ? "Yo:" : chatSeleccionado.getNombreContacto()+":").concat("\n"+msgField.getText());
        StyledDocument doc = mensajes.getStyledDocument();
        SimpleAttributeSet atributos = new SimpleAttributeSet();
        StyleConstants.setAlignment(atributos, emisor ? StyleConstants.ALIGN_RIGHT : StyleConstants.ALIGN_LEFT);

        try {
            doc.insertString(doc.getLength(), msj + "\n", atributos);
        } catch (BadLocationException e) {
            e.printStackTrace();
        }
    }
    
    protected static void setChat(){
        nameLabel.setText(chatSeleccionado.getNombreContacto());
        if(chatSeleccionado.getNombreImagenContacto()!=null){
            setIcono(icon, StartPanel.chat.getNombreImagenContacto());
        }else setIcono(icon,"userSignin.png");
        mensajes = new JTextPane();
        mensajes.setEditable(false);
        mensajes.setContentType("text/html");
        mensajes.setFont(new Font("Dialog", Font.PLAIN, 14));
        mensajes.setPreferredSize(new Dimension(393,450));
        mensajes.setAlignmentX(0.0f);
        mensajes.setAlignmentY(140.0f);
        scroll.setViewportView(mensajes);
    }
    
    private void volver(){
        ((Parent) SwingUtilities.getWindowAncestor(this)).mostrarVentana("start");
    }
    
    private static void setIcono(javax.swing.JButton button, String filename){
        button.setIcon(new ImageIcon("src/main/java/imagenes/"+filename));
        button.setContentAreaFilled(false);
        button.setBorder(null);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton backBtn;
    private javax.swing.JRadioButton bttnEmisor;
    private javax.swing.JRadioButton bttnReceptor;
    private javax.swing.ButtonGroup buttonGroup1;
    private static javax.swing.JButton icon;
    private javax.swing.JPanel infoContacto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel msgBarPanel;
    private javax.swing.JTextField msgField;
    private static javax.swing.JLabel nameLabel;
    private javax.swing.JButton photoBtn;
    private static javax.swing.JScrollPane scroll;
    private javax.swing.JButton sendBtn;
    // End of variables declaration//GEN-END:variables
}
