/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pantallas;

import DTOs.UsuarioDTO;
import excepciones.NegocioException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.text.Document;

/**
 *
 * @author LuisaM
 */
public class LoginPanel extends javax.swing.JPanel {

    private final ImageIcon visibleIcon=new ImageIcon("src/main/java/imagenes/visible_32.png");
    private final ImageIcon invisibleIcon=new ImageIcon("src/main/java/imagenes/invisible_32.png");
    /**
     * Creates new form PanelLogin
     */
    public LoginPanel() {
        initComponents();
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        signInBtn = new javax.swing.JButton();
        logInBtn = new javax.swing.JButton();
        container = new javax.swing.JPanel();
        campoContrasena = new javax.swing.JPasswordField();
        lookBtn = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(393, 700));
        setMinimumSize(new java.awt.Dimension(393, 700));
        setPreferredSize(new java.awt.Dimension(393, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Juatsapp");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("¿No tienes una cuenta?");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, -1, -1));

        signInBtn.setBackground(new java.awt.Color(217, 217, 217));
        signInBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        signInBtn.setForeground(new java.awt.Color(0, 0, 0));
        signInBtn.setText("Registrate");
        signInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInBtnActionPerformed(evt);
            }
        });
        add(signInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, 180, 40));

        logInBtn.setBackground(new java.awt.Color(86, 209, 246));
        logInBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        logInBtn.setForeground(new java.awt.Color(0, 0, 0));
        logInBtn.setText("iniciar sesion");
        logInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInBtnActionPerformed(evt);
            }
        });
        add(logInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 180, 40));

        container.setBackground(new java.awt.Color(217, 217, 217));
        container.setPreferredSize(new java.awt.Dimension(300, 230));

        campoContrasena.setBackground(new java.awt.Color(255, 255, 255));
        campoContrasena.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        campoContrasena.setForeground(new java.awt.Color(0, 0, 0));
        campoContrasena.setMaximumSize(new java.awt.Dimension(250, 70));
        campoContrasena.setMinimumSize(new java.awt.Dimension(200, 70));
        campoContrasena.setPreferredSize(new java.awt.Dimension(250, 40));

        lookBtn.setBackground(new java.awt.Color(153, 153, 153));
        lookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lookBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Contraseña:");

        txtTelefono.setBackground(new java.awt.Color(255, 255, 255));
        txtTelefono.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefono.setMaximumSize(new java.awt.Dimension(250, 70));
        txtTelefono.setMinimumSize(new java.awt.Dimension(200, 70));
        txtTelefono.setPreferredSize(new java.awt.Dimension(250, 40));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Telefono:");

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addComponent(campoContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        add(container, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 220, -1, -1));

        jPanel2.setBackground(new java.awt.Color(86, 209, 246));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 360));
    }// </editor-fold>//GEN-END:initComponents

    private void logInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInBtnActionPerformed
        // TODO add your handling code here:
        if(!txtTelefono.getText().isBlank() || campoContrasena.getPassword().length>0){
            UsuarioDTO u = new UsuarioDTO();
            u.setTelefono(txtTelefono.getText());
            u.setContrasena(String.valueOf(campoContrasena.getPassword()));
            login(u);
        }else 
            JOptionPane.showMessageDialog(null, "No puede dejar campos vacios");
    }//GEN-LAST:event_logInBtnActionPerformed

    private void lookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lookBtnActionPerformed
        // TODO add your handling code here:
        verContra(lookBtn.isSelected());
    }//GEN-LAST:event_lookBtnActionPerformed

    private void signInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInBtnActionPerformed
        // TODO add your handling code here:
        cambiarPanel("signIn");
    }//GEN-LAST:event_signInBtnActionPerformed

    private void iniciar(){
        lookBtn.setIcon(invisibleIcon);
        lookBtn.setVisible(false);
        campoContrasena.getDocument().addDocumentListener(new javax.swing.event.DocumentListener(){
            @Override
            public void insertUpdate(DocumentEvent e) {
                validar(e);
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                validar(e);
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                validar(e);
            }
            private void validar(DocumentEvent e){
                if(e.getDocument().getLength()>0){
                    lookBtn.setVisible(true);
                }else{
                    lookBtn.setVisible(false);
                    verContra(false);
                }
                
            }
        });
    }
    
    private void verContra(boolean flag){
        if(flag){
            campoContrasena.setEchoChar((char) 0);
            lookBtn.setIcon(visibleIcon);
        } else {
            campoContrasena.setEchoChar('\u2022');
            lookBtn.setIcon(invisibleIcon);
        }
            
    }
    private void login(UsuarioDTO usuario){
        UsuarioDTO user;
        try {
            user=Parent.fachadaUsuarios.login(usuario);
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            return;
        }
        if(user!=null){
            Parent.user=user;
            cambiarPanel("start");
        }else
            JOptionPane.showMessageDialog(null, "Contraseña incorrecta");
    }
    private void limpiarPanel(){
        txtTelefono.setText("");
        campoContrasena.setText("");
        lookBtn.setVisible(false);
    }
    private void cambiarPanel(String nombrePanel){
        limpiarPanel();
        ((Parent) SwingUtilities.getWindowAncestor(this)).mostrarVentana(nombrePanel);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField campoContrasena;
    private javax.swing.JPanel container;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logInBtn;
    private javax.swing.JToggleButton lookBtn;
    private javax.swing.JButton signInBtn;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
