/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pantallas;

import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

/**
 *
 * @author LuisaM
 */
public class SignInPanel extends javax.swing.JPanel {

    private final ImageIcon defaultLight=new ImageIcon("src/main/java/imagenes/default.png");
    private final ImageIcon defaultDark=new ImageIcon("src/main/java/imagenes/default_dark.png");
    /**
     * Creates new form SignInPanel
     */
    public SignInPanel() {
        initComponents();
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        nameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dateChooser = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        phoneField = new javax.swing.JTextField();
        passField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        manBtn = new javax.swing.JRadioButton();
        womanBtn = new javax.swing.JRadioButton();
        otherBtn = new javax.swing.JRadioButton();
        streetField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nbhField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        numField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        iconBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(393, 700));
        setMinimumSize(new java.awt.Dimension(393, 700));
        setPreferredSize(new java.awt.Dimension(393, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(217, 217, 217));
        jPanel2.setPreferredSize(new java.awt.Dimension(280, 460));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        jPanel2.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 230, 28));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Telefono:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Contraseña:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Fecha de nacimiento:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));
        jPanel2.add(dateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 230, 28));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Calle:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));
        jPanel2.add(phoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 230, 28));
        jPanel2.add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 230, 28));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Sexo:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        manBtn.setBackground(new java.awt.Color(217, 217, 217));
        btnGroup.add(manBtn);
        manBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        manBtn.setForeground(new java.awt.Color(0, 0, 0));
        manBtn.setText("Hombre");
        jPanel2.add(manBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        womanBtn.setBackground(new java.awt.Color(217, 217, 217));
        btnGroup.add(womanBtn);
        womanBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        womanBtn.setForeground(new java.awt.Color(0, 0, 0));
        womanBtn.setText("Mujer");
        jPanel2.add(womanBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, -1, -1));

        otherBtn.setBackground(new java.awt.Color(217, 217, 217));
        btnGroup.add(otherBtn);
        otherBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        otherBtn.setForeground(new java.awt.Color(0, 0, 0));
        otherBtn.setText("Otro");
        jPanel2.add(otherBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, -1, -1));
        jPanel2.add(streetField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 230, 28));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Colonia:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        nbhField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbhFieldActionPerformed(evt);
            }
        });
        jPanel2.add(nbhField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 100, 28));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Numero:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));
        jPanel2.add(numField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 100, 28));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jPanel1.setBackground(new java.awt.Color(86, 209, 246));

        iconBtn.setBorder(null);
        iconBtn.setBorderPainted(false);
        iconBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                iconBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                iconBtnMouseReleased(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(86, 209, 246));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Agregar foto");
        jButton2.setBorderPainted(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(iconBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(iconBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton2)))
                .addContainerGap(321, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 400));

        cancelBtn.setBackground(new java.awt.Color(81, 81, 81));
        cancelBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(217, 217, 217));
        cancelBtn.setText("cancelar");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 610, 130, 40));

        saveBtn.setBackground(new java.awt.Color(86, 209, 246));
        saveBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(0, 0, 0));
        saveBtn.setText("guardar");
        add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 610, 120, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        cancelar();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void nbhFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbhFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nbhFieldActionPerformed

    private void iconBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconBtnMousePressed
        // TODO add your handling code here:
        iconBtn.setIcon(defaultDark);
    }//GEN-LAST:event_iconBtnMousePressed

    private void iconBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconBtnMouseReleased
        // TODO add your handling code here:
        iconBtn.setIcon(defaultLight);
    }//GEN-LAST:event_iconBtnMouseReleased
    
    private void iniciar(){
        iconBtn.setIcon(defaultLight);
        iconBtn.setContentAreaFilled(false);
    }
    
    private void verificarCamposVacios(){
        saveBtn.setEnabled(nameField.getText().isBlank()||phoneField.getText().isBlank()
                ||passField.getText().isBlank()||dateChooser.getCalendar()==null
                ||(!manBtn.isSelected() && !womanBtn.isSelected() && !otherBtn.isSelected()));
            saveBtn.setEnabled(false);
    }
    
    private void limpiarCampos(){
        nameField.setText("");
        phoneField.setText("");
        passField.setText("");
        dateChooser.setDate(null);
        streetField.setText("");
        nbhField.setText("");
        numField.setText("");
        btnGroup.clearSelection();
    }
    private void cancelar(){
        limpiarCampos();
        ((Parent) SwingUtilities.getWindowAncestor(this)).mostrarVentana("login");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton cancelBtn;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JButton iconBtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton manBtn;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField nbhField;
    private javax.swing.JTextField numField;
    private javax.swing.JRadioButton otherBtn;
    private javax.swing.JTextField passField;
    private javax.swing.JTextField phoneField;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField streetField;
    private javax.swing.JRadioButton womanBtn;
    // End of variables declaration//GEN-END:variables
}
